dia = int(input("Informe um número de 1 a 7: "))
if dia<1 or dia>7 : print("Valor incorreto.")

if dia==1: print('Domingo')
if dia==2: print('Segunda-feira')
if dia==3: print('Terça-feira')
if dia==4: print('Quarta-feira')
if dia==5: print('Quinta-feira')
if dia==6: print('Sexta-feira')
if dia==7: print('Sábado')